name: AHOnlineWorker
trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  tag: '$(Build.BuildId)'

jobs:
- job: BuildImageService
  displayName: Build and publish docker image
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: Docker@2
    displayName: Build an AH Online Worker Image
    inputs:
      containerRegistry: 'DockerHub'
      repository: 'hantse/ahonlineworker'
      command: 'buildAndPush'
      Dockerfile: 'src/workers/AHSync.Worker/Dockerfile'
      buildContext: '.'
      tags: |
        $(tag)
        dev-$(tag)
        dev

- job: BuildImageService
  displayName: Build and publish docker image
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: Docker@2
    displayName: Build an AH Online Dashboard Image
    inputs:
      containerRegistry: 'DockerHub'
      repository: 'hantse/ahonlinedashboard'
      command: 'buildAndPush'
      Dockerfile: 'src/workers/AHSync.Dashboard/Dockerfile'
      buildContext: '.'
      tags: |
        $(tag)
        dev-$(tag)
        dev

- job: BuildImageService
  displayName: Build and publish docker image
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: Docker@2
    displayName: Build an AH Online Admin Service Image
    inputs:
      containerRegistry: 'DockerHub'
      repository: 'hantse/ahonlineadminservice'
      command: 'buildAndPush'
      Dockerfile: 'src/services/Service.Admin/Dockerfile'
      buildContext: '.'
      tags: |
        $(tag)
        dev-$(tag)
        dev                