CREATE TABLE [Auction]
(
	Id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY,
	AuctionId BIGINT NOT NULL,
    [RealmName] NVARCHAR(120) NOT NULL,
    [RealmFaction] INT NOT NULL,
	[ItemName] NVARCHAR(80) NOT NULL,
	[ItemId] INT NOT NULL,
	[ItemRand] INT NULL,
	[ItemSeed] INT NULL,
	[Bid] INT NOT NULL,
	[Buyout] INT NOT NULL,
	[Quantity] INT NOT NULL,
	[TimeLeft] NVARCHAR(80) NOT NULL,
    CreateAt DATETIME NOT NULL DEFAULT GETUTCDATE(),
    CreateBy NVARCHAR(48) NOT NULL,
    DeleteAt DATETIME NULL,
    DeleteBy NVARCHAR(48) NULL,
    UpdateAt DATETIME NULL,
    UpdateBy NVARCHAR(48) NULL
);