
CREATE TABLE [Auction]
(
	Id BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY CLUSTERED,
	AuctionId BIGINT NOT NULL,
    [RealmName] NVARCHAR(120) NOT NULL,
    [RealmFaction] INT NOT NULL,
	[ItemName] NVARCHAR(80) NOT NULL,
	[ItemId] INT NOT NULL,
	[ItemRand] INT NULL,
	[ItemSeed] INT NULL,
	[Bid] INT NOT NULL,
	[Buyout] INT NOT NULL,
	[Quantity] INT NOT NULL,
	[TimeLeft] NVARCHAR(80) NOT NULL,
    CreateAt DATETIME NOT NULL DEFAULT GETUTCDATE(),
    CreateBy NVARCHAR(48) NOT NULL,
    DeleteAt DATETIME NULL,
    DeleteBy NVARCHAR(48) NULL,
    UpdateAt DATETIME NULL,
    UpdateBy NVARCHAR(48) NULL
);

CREATE TABLE [ItemPriceHistory]
(
	Id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY,
	Price BIGINT NOT NULL,
    [RealmName] NVARCHAR(120) NOT NULL,
    [RealmFaction] INT NOT NULL,
	[ItemName] NVARCHAR(80) NOT NULL,
	[ItemId] INT NOT NULL,
	[ItemRand] INT NULL,
	[ItemSeed] INT NULL,
	[DateOf] DATETIME NOT NULL DEFAULT GETUTCDATE(),
    CreateAt DATETIME NOT NULL DEFAULT GETUTCDATE(),
    CreateBy NVARCHAR(48) NOT NULL,
    DeleteAt DATETIME NULL,
    DeleteBy NVARCHAR(48) NULL,
    UpdateAt DATETIME NULL,
    UpdateBy NVARCHAR(48) NULL
);

CREATE TABLE [OperationHistory]
(
	Id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY,
    [RealmName] NVARCHAR(120) NOT NULL,
    [RealmFaction] INT NOT NULL,
    Duration INT NOT NULL,
    Inserted INT NOT NULL,
    Deleted INT NOT NULL,
    Updated INT NOT NULL,
    CreateAt DATETIME NOT NULL DEFAULT GETUTCDATE(),
    CreateBy NVARCHAR(48) NOT NULL,
    DeleteAt DATETIME NULL,
    DeleteBy NVARCHAR(48) NULL,
    UpdateAt DATETIME NULL,
    UpdateBy NVARCHAR(48) NULL
);